server:
  port: 8088
spring:
  application:
    name: eureka

eureka:
  instance:
    # 是否使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # 设置eureka实例名称，建议与配置文件的变量相同，必须和Linux系统域名相同
    hostname: eureka1
  #    hostname: ${HOST_NAME}
  #    status-page-url-path: ${server.servletPath}/info
  #    health-check-url-path: ${server.servletPath}/health
  client:
    healthcheck:
      # 健康检查
      enabled: true
    serviceUrl:
      # eureka注册中心地址
      defaultZone: http://ting:ting@ting.eureka:8080/eureka
    # 是否注册自身
    fetch-registry: false
    # 只允许访问别人，不让其他服务访问自己
    register-with-eureka: true

